version: "3"
services:
  flaskapp:
    image: registry.hub.docker.com/sophietruong92/quick-read-mvp:1.2
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 8192M  
